name: CheckTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Printing php version
        run: php --version
        
      - name: Printing composer version
        run: composer
